title: Nerdisserie
tagline: A nerdy girl's take on baking
email: nerdisserie@gmail.com
author: Heather Pekrul
description: >-
  A nerdy girl's take on baking
baseurl: ""
url: "https://nerdisserie.com"
port: 4001
default_featured_image_path: /images/site/placeholder.jpg
ga_tracking_id: UA-132827607-1

# Social
avatar_url: images/site/share-sq.jpg
twitter_username: nerdisserie
github_username:  heatherpekrul
github_url: https://github.com/heatherpekrul/nerdisserie
facebook_page: nerdisserie

# Navigation
navigation_header:
  Home: /
  About: /about/
  Tools: /tools/
  Contact: /contact/

# Footer
footer:
  copyright: Copyright 2019 Heather Pekrul. All rights reserved.

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - js/
  - scss/
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock

# Build Commands
# JS/CSS assets: webpack
# Local Jekyll build and serve: bundle exec jekyll serve
# Production Jekyll build: JEKYLL_ENV=production jekyll build
